# Scala CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/sample-config/ for more details
#
version: 2
jobs:
  build:
    docker:
      # primary container
      - image: ansingh7115/avram

      # database container
      - image: circleci/postgres:9.6-alpine-ram
        environment:
          POSTGRES_USER: avram
          POSTGRES_PASSWORD: test
          POSTGRES_DB: testdb

    working_directory: ~/repo

    environment:
      # Customize the JVM maximum heap limit
      JVM_OPTS: -Xmx3200m
      APPENGINE_SDK_HOME: /home/gcloud/appengine-java-sdk-1.9.67
      TERM: dumb

    steps:
      - checkout

      - run: cd db && ./run-liquibase.sh

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "project/Dependencies.scala" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: cat /dev/null | sbt test:compile

      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies--{{ checksum "project/Dependencies.scala" }}

      # run tests!
      - run: cat /dev/null | sbt test:test